In [4]:
function multiplicacion(u,v)
    if length(u)==length(v)
        p=0
        for i ∈ eachindex(u)
          p=p+(u[i]*v[i])
            end 
        p
        else 
        println("u y v deben de ser del mismo tamaño")
        end 
    end 

multiplicacion (generic function with 1 method)

In [5]:
u=[1,2,3,4,5]


5-element Array{Int64,1}:
 1
 2
 3
 4
 5

In [6]:
v= [5,6,7,8,9]

5-element Array{Int64,1}:
 5
 6
 7
 8
 9

In [7]:
multiplicacion(u,v)

115

In [8]:
sum(u.*v)

115

In [9]:
u=[1,2]


2-element Array{Int64,1}:
 1
 2

In [10]:
v=[3,4,5]

3-element Array{Int64,1}:
 3
 4
 5

In [11]:
multiplicacion(u,v)

u y v deben de ser del mismo tamaño


In [12]:
A =[1,-2]

2-element Array{Int64,1}:
  1
 -2

In [13]:
B=[3,5]

2-element Array{Int64,1}:
 3
 5

In [14]:
A+B

2-element Array{Int64,1}:
 4
 3

In [15]:
hcat(B)

2×1 Array{Int64,2}:
 3
 5

In [16]:
multiplicacion(A,B)

-7

In [17]:
A=[1,-2]

2-element Array{Int64,1}:
  1
 -2

In [18]:
B=[3,5]

2-element Array{Int64,1}:
 3
 5

In [19]:
B'

1×2 RowVector{Int64,Array{Int64,1}}:
 3  5

In [20]:
A.*B'

2×2 Array{Int64,2}:
  3    5
 -6  -10

In [21]:
A=[1,-2,3,5]

4-element Array{Int64,1}:
  1
 -2
  3
  5

In [22]:
A(2,2)

LoadError: MethodError: objects of type Array{Int64,1} are not callable
Use square brackets [] for indexing an Array.

In [23]:
A[2,2]

LoadError: BoundsError: attempt to access 4-element Array{Int64,1} at index [2, 2]

In [24]:
zeros(2,2)

2×2 Array{Float64,2}:
 0.0  0.0
 0.0  0.0

In [25]:
A=arreglo(2,2)

LoadError: UndefVarError: arreglo not defined

In [26]:
hcat(A)

4×1 Array{Int64,2}:
  1
 -2
  3
  5

In [27]:
hcat(A)

4×1 Array{Int64,2}:
  1
 -2
  3
  5

In [28]:
vcat(A)

4-element Array{Int64,1}:
  1
 -2
  3
  5

In [29]:
eye(2)

2×2 Array{Float64,2}:
 1.0  0.0
 0.0  1.0

In [30]:
eye(A)

LoadError: MethodError: no method matching eye(::Array{Int64,1})
Closest candidates are:
  eye(::Type{Diagonal{T}}, ::Int64) where T at linalg/diagonal.jl:289
  eye(::Type{T}, ::Integer) where T at array.jl:290
  eye(::Type{T}, ::Integer, ::Integer) where T at array.jl:277
  ...

In [31]:
A=eye(1,-2,3,5)

LoadError: MethodError: no method matching eye(::Int64, ::Int64, ::Int64, ::Int64)
Closest candidates are:
  eye(::Type{T}, ::Integer, ::Integer) where T at array.jl:277
  eye(::Integer, ::Integer) at array.jl:289
  eye(::Type{Diagonal{T}}, ::Int64) where T at linalg/diagonal.jl:289
  ...

In [32]:
A=reshape[(1,-2,3,5), 2,2]

LoadError: MethodError: no method matching getindex(::Base.#reshape, ::NTuple{4,Int64}, ::Int64, ::Int64)

In [33]:
A=[1,-2]

2-element Array{Int64,1}:
  1
 -2

In [34]:
B=[3,5]

2-element Array{Int64,1}:
 3
 5

In [35]:
bsxfun(+,A,B)

LoadError: UndefVarError: bsxfun not defined

In [36]:
sparse(A,B)

LoadError: MethodError: no method matching sparse(::Array{Int64,1}, ::Array{Int64,1})
Closest candidates are:
  sparse(::AbstractArray{Ti<:Integer,1}, ::AbstractArray{Ti<:Integer,1}, ::AbstractArray{Tv,1}, ::Integer, ::Integer, ::Any) where {Tv, Ti<:Integer} at sparse/sparsematrix.jl:476
  sparse(::AbstractArray{T,1} where T, ::AbstractArray{T,1} where T, ::AbstractArray{T,1} where T, ::Integer, ::Integer, ::Any) at sparse/sparsematrix.jl:513
  sparse(::Any, ::Any, ::Number) at sparse/sparsematrix.jl:685
  ...

In [37]:
sparse(A)

2-element SparseVector{Int64,Int64} with 2 stored entries:
  [1]  =  1
  [2]  =  -2

In [38]:
sparse(B)

2-element SparseVector{Int64,Int64} with 2 stored entries:
  [1]  =  3
  [2]  =  5

In [39]:
A=rand(2,2)

2×2 Array{Float64,2}:
 0.725879  0.918125
 0.107366  0.232296

In [40]:
B=rand(2,2)

2×2 Array{Float64,2}:
 0.367786  0.71426  
 0.532837  0.0789259

In [48]:
C=A.*B

2×2 Array{Float64,2}:
 0.266968   0.65578  
 0.0572085  0.0183341

In [49]:
writedldm("C",'|')

LoadError: UndefVarError: writedldm not defined

In [50]:
writedlm


writedlm (generic function with 5 methods)

In [58]:
writedlm("C.txt",C,'|')

In [59]:
C.txt

LoadError: type Array has no field txt

In [60]:
readdlm("c.txt")

2×1 Array{Any,2}:
 "0.26696805852247313|0.6557799373177088"   
 "0.057208508037252345|0.018334129555750724"